"""add unique constraints

Revision ID: c9a1d5eb04c4
Revises: 32379aecf7cf
Create Date: 2026-05-24 14:19:54.280504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a1d5eb04c4'
down_revision: Union[str, Sequence[str], None] = '32379aecf7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('id_token_uq', 'session_tokens', ['user_id', 'session_token'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('id_token_uq', 'session_tokens', type_='unique')
    # ### end Alembic commands ###
