"""add cascade on_delete in foreign key

Revision ID: baec9b8bbe93
Revises: 7ee9de17b7bd
Create Date: 2026-05-26 12:51:43.616087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baec9b8bbe93'
down_revision: Union[str, Sequence[str], None] = '7ee9de17b7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('session_tokens_user_id_fkey'), 'session_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'session_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('session_tokens_user_id_fkey'), 'session_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
