"""add foreign key on session_tokens

Revision ID: 7ee9de17b7bd
Revises: c9a1d5eb04c4
Create Date: 2026-05-26 12:48:17.136500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee9de17b7bd'
down_revision: Union[str, Sequence[str], None] = 'c9a1d5eb04c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'session_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_tokens', type_='foreignkey')
    # ### end Alembic commands ###
